config/routes.rb
SampleApp::Application.routes.draw do

  mount Messaging::Engine => "/messaging"

Messaging::Engine.routes.draw do
  resources :messages do
    member do
      delete 'trash'
      post 'untrash'
    end
    collection do
      delete 'trash'
    end
  end
  post 'search' => 'messages#search'
end

  resources :messages
  resources :conversations

  resources :books
  resources :notes
  resources :parentpages
  resources :subpages
  resources :relatedpages
  resources :interests
  resources :activities

  resources :rooms  
  match '/party/:id', :to => "rooms#party", :as => :party, :via => :get

  resources :users do
    member do
      get :following, :followers, :interests
    end
  end

  resources :pages do
    member do
      post :follow
      post :unfollow
      get :shownotes
    end
  end

  resources :notes do
    member do
      post :upvote
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :notes, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
      
  root to: 'static_pages#welcome'

  match '/interests' => 'users#interests'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
      
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :page
  belongs_to :user
  make_voteable
  default_scope -> { order('created_at DESC') }
  validates :title, presence: true
  validates :content, presence: true
  validates :user_id, presence: true
  attr_accessible :content, :user_id, :page, :title
  include PublicActivity::Common
  #tracked owner: Proc.new{ |controller, model| controller.current_user }
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  include ActionView::Helpers::TextHelper

before_filter :authorize, :except => [:show, :new, :create, :upvote]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notes }
    end
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    @note = Note.find(params[:id])
    @title = @note.title

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @note }
    end
  end

  # GET /notes/new
  # GET /notes/new.json
  def new
    @note = Note.new
    @page = Page.find(params[:id]) # gets the value of the parent page

    respond_to do |format|
      flash.now[:notice] = "<span class='glyphicon icon-chevron-left'></span> Back to <a href='#{url_for(@page)}'>#{@page.name}</a>".html_safe      
      format.html # new.html.erb
      format.json { render json: @note }
    end
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])
  end

  # POST /notes
  # POST /notes.json
  def create
    #@note = Note.new(params[:note])

    if params[:parent].present?
    @page = Page.find(params[:parent]) # gets the value of the parent page from _form.html.erb
        @note = current_user.notes.build(:title => params[:title], :content => params[:content])
        @note.page = @page
        @note.save        
    end

    respond_to do |format|
      if @note.save
        @note.create_activity :create, owner: current_user #saves the user activity        
        format.html { redirect_to @page, notice: 'Note was successfully created.' }
        format.json { render json: @page, status: :created, location: @note }
      else
        format.html { render action: "new" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.json
  def update
    @note = Note.find(params[:id])

    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def upvote
    @note = Note.find params[:id]
    current_user.up_vote(@note)
    @note.create_activity(:upvoted, owner: current_user)
    flash[:message] = 'Thanks for voting!'
    redirect_to note_path(@note)
  rescue MakeVoteable::Exceptions::AlreadyVotedError
    flash[:error] = 'Already voted!'
    redirect_to note_path(@note)
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    respond_to do |format|
      @note.create_activity :destroy, owner: current_user #saves the user activity              
      format.html { redirect_to @note.page }
      format.json { head :no_content }
    end
  end

private

  def authorize
    @note = Note.find(params[:id])
      
    if(@note.user != current_user)
      render text:"NOT authorized"
    end
  end

end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_draft.html.erb
<li>  
  <span class="content">   
        <p><br><%= raw(note.content) %></p>
        <span class="timestamp"><%= time_ago_in_words(note.created_at) %> ago</span>
        <% if current_user?(note.user) %>
          <%= link_to "delete", note, method: :delete,
                                     data: { confirm: 'You sure?' },
                                     title: note.content %>
        <% end %>   
      <hr>
  </span>      
</li>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="col-md-9">

<form action="save.php" method="get">
    <div class="field">
    Title<br><br> <%= text_field_tag(:title) %>
  </div>
  <textarea class="textarea" id="content" name="content" placeholder="Enter text ..." style="min-height:400px;"></textarea>
  <input type="hidden" id="parent" name="parent" value=<%= params[:id] %> />
  <input type="submit" class="btn btn-primary" />
</form> 

<script type="text/javascript">
  $('#content').wysihtml5({
  "font-styles": false, //Font styling, e.g. h1, h2, etc. Default true
  "emphasis": true, //Italics, bold, etc. Default true
  "lists": false, //(Un)ordered lists, e.g. Bullets, Numbers. Default true
  "html": false, //Button which allows you to edit the generated HTML. Default false
  "link": true, //Button to insert a link. Default true
  "image": false, //Button to insert an image. Default true,
  "color": false //Button to change color of font  
});
</script>

  </div>
 </div>

<% end %>

app/views/notes/_note.html.erb
  <div class="row">
    <div class="col-md-7">
      <div class="notes content">
        

      <% if note.title.present? %>
        <h4 style="padding-bottom:2px;"><%= link_to note.title, note %></h4>
      <% end %>
          <% if note.content.length > 1200 %>
            <p><%= raw(truncate(note.content, length: 1200)) %>
            <u><%= link_to "more", note %></u></p>
          <% else %>
            <p><%= raw(note.content) %></p>
          <% end %>
            <span class="timestamp"><%= link_to (note.user.name), note.user %>, </span>  
            <span class="timestamp"><%= time_ago_in_words(note.created_at) %> ago</span>
            <span class="timestamp"><%= link_to (note.page.name), note.page %></span>
            <% if current_user?(note.user) %>
              <%= link_to "delete", note, method: :delete,
                                         data: { confirm: 'You sure?' },
                                         title: note.content %>
            <% end %>   

      </div>
    </div>

    <% if note.user.present? %>

    <div class="col-md-3">
      <div class="notesprofile">
        <table cellpadding="5">
        <tr>
        <td>
        <%= link_to (image_tag note.user.avatar.url(:thumb), :size => "40x40", class: "avatar-nav"), note.user %>


        </td>
        <td>
 <%= link_to (note.user.name), note.user %>
        <br>
        <span class="glyphicon icon-thumbs-up"></span> <%= note.votes %>
        <% if current_user.present? %>
        <%= link_to "Upvote", upvote_note_url(note), :method => :post %>  
        <% end %>


        </td>
        </tr>
        </table>
       
        </div>    
      </div>   
    <% end %>   
 

    </div>    

app/views/notes/edit.html.erb
<div class="container">
	<h1>Editing note</h1>

	<% if current_user.present? %>
	  <%= render 'form' %>
	<% else %>
	  <p>You have to be signed in to edit notes.</p>  
	<% end %>
</div>

app/views/notes/index.html.erb
<h1>Listing notes</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th>Page</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notes.each do |note| %>
  <tr>
    <td><%= truncate note.content, length: 100 %></td>
    <td><%= note.user.name %></td>
    <td><%= note.page.name %></td>
    <td><%= link_to 'Show', note %></td>
    <td><%= link_to 'Edit', edit_note_path(note) %></td>
    <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<div class="container">
	<div class="row">
	  <div class="col-md-12">

	  <h3>New Note - <%= @page.name %></h3>

	  <% if current_user.present? %>
	    <%= render 'form' %>
	  <% else %>
	    <p>You have to be signed in to write notes.</p><br><br>  
	    <%= link_to "Sign in", signin_path %>
	  <% end %>

	  </div>
	</div>
</div>

app/views/notes/show.html.erb
<div class="container">
  <div class="row" style="padding-top:40px;">
    <div class="col-md-8">
      <div class="note">
        <div class="noteheader">
          <div class="notesubjectbar">
            <p style="color:black"><b><%= @note.page.name %> Notes</b></p>
          </div>  

          <% if @title.present? %>
              <h4><%= @title %></h4>
            <% end %>
            <p>
              <% if @note.page %>
                <span style="color:gray;font-size:1.0em;">By <%= link_to (@note.user.name), @note.user %> in <%= link_to (@note.page.name), @note.page %> <%= time_ago_in_words(@note.created_at) %> ago</span>
              <% end %>
              <% if current_user?(@note.user) %>
                <%= link_to 'Edit', edit_note_path(@note) %>
              <% end %>
            </p>
        </div>

        <div class="notebody">  
          <p>
            <hr><%= raw(@note.content) %>
          </p>    
        </div>

        <div class="notefooter">
          <%= link_to (image_tag @note.user.avatar.url(:thumb), :class => "user_small"), @note.user %>
          <b><%= link_to (@note.user.name), @note.user %></b>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>