config/routes.rb
SampleApp::Application.routes.draw do

  mount Messaging::Engine => "/messaging"

Messaging::Engine.routes.draw do
  resources :messages do
    member do
      delete 'trash'
      post 'untrash'
    end
    collection do
      delete 'trash'
    end
  end
  post 'search' => 'messages#search'
end

  resources :messages
  resources :conversations

  resources :books
  resources :notes
  resources :parentpages
  resources :subpages
  resources :relatedpages
  resources :interests
  resources :activities

  resources :rooms  
  match '/party/:id', :to => "rooms#party", :as => :party, :via => :get

  resources :users do
    member do
      get :following, :followers, :interests
    end
  end

  resources :pages do
    member do
      post :follow
      post :unfollow
      get :shownotes
    end
  end

  resources :notes do
    member do
      post :upvote
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :notes, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
      
  root to: 'static_pages#welcome'

  match '/interests' => 'users#interests'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
      
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  before_filter :get_mailbox, :get_box, :get_user
  before_filter :check_current_subject_in_conversation, :only => [:show, :update, :destroy]

  def index

    @conversations = @mailbox.conversations

    respond_to do |format|
      format.html { render @conversations if request.xhr? }
    end
  end

    def show

    if @box.eql? 'trash'
      @receipts = @mailbox.receipts_for(@conversation).trash
    else
      @receipts = @mailbox.receipts_for(@conversation).not_trash
    end
    render :action => :show
    @receipts.mark_as_read
  end


  def update
    if params[:untrash].present?
    @conversation.untrash(@user)
    end

    if params[:reply_all].present?
      last_receipt = @mailbox.receipts_for(@conversation).last
      @receipt = @user.reply_to_all(last_receipt, params[:body])
    end

    if @box.eql? 'trash'
      @receipts = @mailbox.receipts_for(@conversation).trash
    else
      @receipts = @mailbox.receipts_for(@conversation).not_trash
    end
    redirect_to :action => :show
    @receipts.mark_as_read

  end

  def destroy

    @conversation.move_to_trash(@user)

    respond_to do |format|
      format.html {
        if params[:location].present? and params[:location] == 'conversation'
          redirect_to conversations_path(:box => :trash)
	else
          redirect_to conversations_path(:box => @box,:page => params[:page])
	end
      }
      format.js {
        if params[:location].present? and params[:location] == 'conversation'
          render :js => "window.location = '#{conversations_path(:box => @box,:page => params[:page])}';"
	else
          render 'conversations/destroy'
	end
      }
    end
  end

  private

  def get_user
    @user = current_user
  end

  def get_mailbox
    @mailbox = current_user.mailbox
  end

  def get_box
    if params[:box].blank? or !["inbox","sentbox","trash"].include?params[:box]
      params[:box] = 'inbox'
    end

    @box = params[:box]
  end

  def check_current_subject_in_conversation
    @conversation = Conversation.find_by_id(params[:id])

    if @conversation.nil? or !@conversation.is_participant?(@user)
      ##redirect_to conversations_path(:box => @box)
      puts "can't find this conversation"
    return
    end
  end

end

app/views/conversations/_conversation.html.erb
<div class="container">

  <%= div_for(conversation, :class =>"#{ 'unread ' if conversation.is_unread?(@user) }") do %>

  <div class="row">
    <div class="col-md-1">
      
      <% conversation.recipients.each do |recipient| %>
       <%= link_to image_tag(recipient.avatar.url(:thumb),
                              :size => "50x50",
                              :alt => recipient.name), recipient if recipient.id != current_user.id %>
      <% end %>
    </div>

    <div class="col-md-2">

      <header>
            <% conversation.recipients.each do |recipient| %>

        <h5>
          <%= recipient.name if recipient.id != current_user.id %>
        </h5>
            <% end %>

          <%= time_ago_in_words(conversation.updated_at) %> ago
      </header>
        </div> 

      <div class="col-md-9" style="margin-top:10px;">
        <%= link_to(raw(truncate(strip_tags(conversation.last_message.body), :length => 200)), conversation_path(conversation.id,:box => @box,:page => params[:page])) %>
      </div>

    </div>
    <hr>

  <% end %>

</div>

app/views/conversations/_conversation_full.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">

      <h4>
        <%= link_to "Inbox", "../conversations" %> > Conversation with
              <% conversation.recipients.each do |recp| %>
          <%= recp.name if recp.id != current_user.id %>
        <% end %>
      </h4>
      <hr>

      <h3>
        <%= conversation.subject %>
      </h3>

      <hr class="soften">
      <div class="messages">
        <% @receipts.each do |receipt| %>
          <p><%= render receipt.message %>
          <br></p>
        <% end %>

        <% unless @box.eql?'trash' %>
        <br>
        <%= form_tag conversation_path(conversation), :method => :put, :class => "cont_conversation" do %>
        <% if @receipt and @receipt.errors.any? %>
          <div class="error">
            <h2>
              <%= pluralize(@receipt.errors.count, "error") %> prohibited this message from being sent:
            </h2>
            <ul>
              <% @receipt.errors.full_messages.each do |msg| %>
              <li>
                <%= msg %>
              </li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="editor">
          <%= text_area_tag :body, nil,:rows =>6, :cols=> 53, :class => "required form_tag" %>
        </div>
        <div class="actions">
          <%= submit_tag 'Send New Message', :name => :reply_all,:class => "btn" %>
        </div>
        <% end %>
        <%end %>
      </div>
    </div>

    <div class="col-md-4">
      <div class="participants">
        <% conversation.recipients.each do |recp| %>
          <%= link_to image_tag(recp.avatar.url(:thumb), :title=>recp.name, :alt => recp.name), recp if recp.id != current_user.id %>
        <% end %>
        <br><br>
        <%= link_to "Video Call", "../party/1", :class => "btn btn-large btn-primary" %>    
      </div>
    </div>
  </div>
</div>

app/views/conversations/index.html.erb
<div class="container">
	<div class="conversations">
		<h4>Inbox</h4>
		<%= current_user.name %>
		<br><hr>
	  <% if @conversations.present? %>	
	  <%= render @conversations %>
	  <% else %>
	  <p>Can't seem to find the conversations</p>
	  <% end %>
	</div>
</div>

app/views/conversations/show.html.erb
<div class="conversation_full">  
  <%= render :partial => 'conversation_full', :locals =>{:conversation => @conversation} %>
</div>